version: "3.8"
services:
  node:
    build: ./app
    volumes:
      - ./app:/app
    tty:  true
    env_file:
      - ./app/.env
    ports:
      - 3000:3000

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    volumes:
      - db_data:/var/lib/posrgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  db_data: {}
